set-option -sa terminal-overrides ",xterm*:Tc"

# Do I really need to mouse?
set -g mouse on

# Change prefix to C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Change some default key bindings
bind-key f resize-pane -Z

# Make the session name the title of the window
set -g set-titles on
set -g set-titles-string "#{session_name}"

# Numbering, makeing it 1 indexed makes it so much easier
# reading the numbers
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Setup pane splitting keymappings
bind '"' split-window -v -c "#{pane_currnet_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable VI mode
setw -g mode-keys vi
bind C-Space copy-mod
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -i -sel c"

# Setup the color theme
set -g @colors-base16 'atelier-dune'

# I use some plugins to make it behave as I wnat it to
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tinted-theming/base16-tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

